#!/bin/bash

declare -a cydia
cydia=($CYDIA)

/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.BTServer.map.plist
/bin/launchctl load /System/Library/LaunchDaemons/com.apple.BTServer.map.plist

if [[ ${CYDIA+@} ]]; then
	eval "echo 'finish:restart' >&${cydia[0]}"
fi

exit 0
